---
# tasks file for git-clone-branches
- name: Cloning {{ project_name }} into {{ dst_dir }}
  git:
    repo: "{{ project_url }}"
    dest: "{{ dst_dir }}/{{ project_name }}-{{ branch_item }}"
    version: "{{ branch_item }}"
  loop: "{{ branches }}"
  loop_control:
    loop_var: branch_item
 
- name: Pushing {{ project_name }}, branch {{ branch_item }} into Gerrit
  shell:
    executable: /bin/sh
    chdir: "{{ dst_dir }}/{{ project_name }}-{{ branch_item }}"
    cmd: |
      git config user.name "Admin"
      git config user.email "admin@example.com"
      git remote add gerrit http://admin:secret@gerrit:8080/{{ project_prefix }}/{{ project_name }}
      git push -f --set-upstream gerrit +HEAD:{{ branch_item }}
  loop: "{{ branches }}"
  loop_control:
    loop_var: branch_item
