---
# tasks file for create-tf-projects
- name: Create directory for tf projects
  file:
    path: /tmp/tf-projects
    state: directory
    mode: '0775'

- name: Create TF repositories
  include_role:
    name: create_project
  vars:
    project: "{{ item.repo }}"
  loop: "{{ tf_projects }}"

- name: clone all needed tf projects
  include_role:
    name: git-clone-branches
  vars:
    project_name: "{{ item.name }}"
    project_prefix: "{{ item.repo_prefix }}"
    project_url: "{{ item.url  }}"
    branches:
      - "R5.0"
      - "R5.1"
      - "master"
  when: '"all" in item.branch'
  loop: "{{ tf_projects }}"

- name: clone all needed tf projects
  include_role:
    name: git-clone-branches
  vars:
    project_name: "{{ item.name }}"
    project_prefix: "{{ item.repo_prefix }}"
    project_url: "{{ item.url  }}"
    branches:
      - "master"
  when: '"master" in item.branch'
  loop: "{{ tf_projects }}"

- name: clone all needed tf projects
  include_role:
    name: git-clone-branches
  vars:
    project_name: "{{ item.name }}"
    project_prefix: "{{ item.repo_prefix }}"
    project_url: "{{ item.url  }}"
    branches:
      - "contrail_dpdk_17_02"
      - "contrail_dpdk_17_05"
      - "contrail_dpdk_17_11"
      - "contrail_dpdk_17_11_3"
      - "contrail_dpdk_18_05_1"
      - "master"
  when: '"dpdk" in item.branch'
  loop: "{{ tf_projects }}"
